[build-system]
requires = ["setuptools>=42.0", "wheel", "anytree>=2.8.0"]
build-backend = "setuptools.build_meta"

[tool.pytest.ini_options]
#addopts = "--cov=pyhdl2"
addopts = "-s -v"
testpaths = [
    "tests",
    ]

[tool.mypy]
mypy_path = "src"
check_untyped_defs = true
disallow_any_generics = true
ignore_missing_imports = false
no_implicit_optional = true
show_error_codes = true
strict_equality = true
warn_redundant_casts = true
warn_return_any = true
warn_unreachable = true
warn_unused_configs = true
no_implicit_reexport = true
